apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: expense-tracker
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres (base64 encoded)
  POSTGRES_PASSWORD: dmlzaG51 # vishnu (base64 encoded)
  POSTGRES_DB: ZXhwZW5zZV9kYg== # expense_db (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: expense-tracker
type: Opaque
data:
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JFeHBlbnNlQXBwVGhhdElzTG9uZ0Vub3VnaEZvckhTMjU2QWxnb3JpdGht # mySecretKeyForExpenseAppThatIsLongEnoughForHS256Algorithm (base64 encoded)
